### ISSUE TITLE
Some question about ffmpeg

### ISSUE THREAD

**Issue by My-captain** [PixxxeL/django-ffmpeg#1]
Hi,PixxxeL.
I'm a CS student from China.Can i use the django-ffmpeg module to encode mp4/flv video file to stream server?
When i run the command "ConvertingCommand(match_by='name', match_regex='.*', command='/usr/bin/ffmpeg -hide_banner -nostats -i %(input_file)s -target film-dvd %(output_file)s', convert_extension='mp4').save()" you provided in the readme,It just convert the file format?

**Comment by PixxxeL** [comment]
Hi!
In my opinion, yes. You may use this module for streaming if ffmpeg tool it resolve. Read ffmpeg help as `ffmpeg --help` in shell or find [manual](https://trac.ffmpeg.org/wiki/StreamingGuide) in web.

Sorry for my late response.

**Comment by My-captain** [comment]
@PixxxeL Thanks very much.
