### ISSUE TITLE
Way to catch error: Invalid data found when processing input

### ISSUE THREAD

**Issue by kvnramirez** [PixxxeL/django-ffmpeg#2]
Hi, I was wondering if there is a way to conversion errors from ffmpeg, errors like: Invalid data found when processing input when the files is corrupted or invalid and then set the convert_status to error? Because module always set it as success even when it failed and there's no output.

**Comment by PixxxeL** [comment]
Add feature in version 0.0.15. Must define `-xerror` in ConvertingCommand
