### ISSUE TITLE
ImportError: cannot import name 'ugettext' from 'django.utils.translation'

### ISSUE THREAD

**Issue by shamspias** [PixxxeL/django-ffmpeg#4]
please change 

`from django.utils.translation import ugettext as _`
to 
`from django.utils.translation import gettext_lazy as _`

in models and admin

**Comment by PixxxeL** [comment]
Thanks! Temporary in branch [translation-fixing](https://github.com/PixxxeL/django-ffmpeg/tree/translation-fixing). Need checking compatible in previous versions. Do it later.

**Comment by shamspias** [comment]
> Thanks! Temporary in branch [translation-fixing](https://github.com/PixxxeL/django-ffmpeg/tree/translation-fixing). Need checking compatible in previous versions. Do it later.

Thanks for the faster replay.
